namespace TF2ItemGenerator;

using System;
using System.IO;
using System.Xml;
using System.Collections.Generic;

internal static class Name
{
    public static readonly string[] nameCategories = { "prefix", "suffix" };

    private static XmlDocument? doc = null;
    private static XmlDocument Initialize()
    {
        XmlDocument doc = new();
        doc.Load(File.GetCurrentDirectory());
        return doc;
    }
    public static string GetRandomName()
    {
        doc ??= Initialize();
    }


}


public static class Data
{
    public static readonly string[] indexToString = { "prefix", "suffix" };
    public static readonly Dictionary<string, string[]> names = new()
    {
        ["prefix"] = new string[]
        {
            "Holy", 
            "Beggar's", 
            "Black", 
            "Liberty",
			"Cow", 
            "Soldier's",
            "Killing",
            "Baby Face's", 
            "Soda", 
            "Back", 
            "Panic", 
            "Buff", 
            "Panic", 
            "Pain",
			"Disciplinary", 
            "Rubber", 
            "Market", 
            "Iron", 
            "Escape", 
            "Lumbricus", 
            "Flame", 
            "Dragon's", 
            "Reserve",
			"Flare", 
            "Scorch", 
            "Thermal", 
            "Gas", 
            "Postal", 
            "Sharpened", 
            "Third", 
            "Neon", 
            "Hot", 
            "Grenade",
			"Ali Baba's", 
            "Loose", 
            "B.A.S.E", 
            "Scottish", 
            "Splendid", 
            "Tide", 
            "Scotsman's", 
            "Ullapool",
			"Claidheamh", 
            "Persian", 
            "Brass", 
            "Huo-Long", 
            "Family", 
            "Robo-", 
            "Dalokohs", 
            "Buffalo Steak",
			"Second", 
            "Apoco-", 
            "Killing", 
            "Gloves", 
            "Bread", 
            "Boxing", 
            "Fists of", 
            "Eviction", 
            "Frontier",
			"Pomson", 
            "Rescue", 
            "Giger", 
            "Short", 
            "Golden", 
            "Southern", 
            "Eureka", 
            "Organ", 
            "Crusader's",
			"Quick-", 
            "Medi", 
            "Vita-", 
            "Solemn", 
            "Sniper", 
            "AWPer", 
            "Fortified", 
            "Sydney", 
            "Bazaar", 
            "Shooting",
			"Hitman's", 
            "Self-Aware", 
            "Darwin's", 
            "Cozy", 
            "Cleaner's", 
            "Tribalman's", 
            "Big", 
            "Black", 
            "Eternal",
			"Wanga", 
            "Conniver's", 
            "Big", 
            "Spy-", 
            "Enthusiast's", 
            "Cloak and", 
            "Dead", 
            "Invis", 
            "Snack", 
            "Red-Tape",
			"Frying", 
            "Freedom", 
            "Bat Outta", 
            "Memory",
            "Ham", 
            "Golden Frying", 
            "Necro", 
            "Crossing", 
            "Prinny",
			"Mad"
        },
        ["suffix"] = new string[]
        {
            "Guillotine", 
            "Cola", 
            "Milk", 
            "Cane", 
            "Basher", 
            "Blade", 
            "Stick", 
            "Assassin", 
            "Launcher", 
            "Box",
		    "Mangler", 
            "Bazooka", 
            "Strike", 
            "Shooter", 
            "Boats", 
            "Backup", 
            "Treads", 
            "Jumper", 
            "Action", 
            "Train",
		    "Plan", 
            "Thrower", 
            "Napalmer", 
            "Fury", 
            "Blower", 
            "Attack", 
            "Pummeler", 
            "Scratcher", 
            "Degree", 
            "Annihilator",
		    "Hand", 
            "Booties", 
            "Cannon", 
            "Bomber", 
            "Resistance", 
            "Targe", 
            "Headtaker", 
            "Nine Iron", 
            "Skullcutter",
		    "Curtain", 
            "Beast", 
            "Heater", 
            "Business", 
            "Bar", 
            "Sandvich", 
            "Banana", 
            "Gloves", 
            "of Boxing", 
            "Fists",
		    "Steel", 
            "Spirit", 
            "Bite", 
            "Ranger", 
            "Justice", 
            "Hospitality", 
            "Effect", 
            "Crossbow", 
            "Vow", 
            "Rifle",
		    "Sleeper", 
            "Compound", 
            "Bargain", 
            "Star", 
            "Heatmaker", 
            "Carbine", 
            "Shield", 
            "Camper", 
            "Shiv", 
            "Dresser",
		    "Prick", 
            "Reward", 
            "Kunai", 
            "Watch", 
            "Ringer", 
            "and Dagger", 
            "Pan", 
            "Staff", 
            "Hell", 
            "Maker", 
            "Shank",
		    "Guard", 
            "Machete", 
            "Pain-Bringer"
        }
    };

    private static readonly Random random = new();
    public static string RandomName()
        => names["suffix"][random.Next(names["suffix"].Length)]
}