using System;
namespace TF2ItemGenerator;
public static class Data
{
    static readonly Random Random = new();
    public static string[][] names = 
    {
        new string[] 
        { 
            "Force-A-", 
            "Pretty Boy's", 
            "Flying", 
            "Candy",
			"Boston", 
            "Battalion's Backup", 
            "Pain-Bringing",
            "Holy", 
            "Beggar's", 
            "Black", 
            "Liberty",
			"Cow", 
            "Soldier's",
            "Killing",
            "Baby Face's", 
            "Soda", 
            "Back", 
            "Panic", 
            "Buff", 
            "Panic", 
            "Pain",
			"Disciplinary", 
            "Rubber", 
            "Market", 
            "Iron", 
            "Escape", 
            "Lumbricus", 
            "Flame", 
            "Dragon's", 
            "Reserve",
			"Flare", 
            "Scorch", 
            "Thermal", 
            "Gas", 
            "Postal", 
            "Sharpened", 
            "Third", 
            "Neon", 
            "Hot", 
            "Grenade",
			"Ali Baba's", 
            "Loose", 
            "B.A.S.E", 
            "Scottish", 
            "Splendid", 
            "Tide", 
            "Scotsman's", 
            "Ullapool",
			"Claidheamh", 
            "Persian", 
            "Brass", 
            "Huo-Long", 
            "Family", 
            "Robo-", 
            "Dalokohs", 
            "Buffalo Steak",
			"Second", 
            "Apoco-", 
            "Killing", 
            "Gloves", 
            "Bread", 
            "Boxing", 
            "Fists of", 
            "Eviction", 
            "Frontier",
			"Pomson", 
            "Rescue", 
            "Giger", 
            "Short", 
            "Golden", 
            "Southern", 
            "Eureka", 
            "Organ", 
            "Crusader's",
			"Quick-", 
            "Medi", 
            "Vita-", 
            "Solemn", 
            "Sniper", 
            "AWPer", 
            "Fortified", 
            "Sydney", 
            "Bazaar", 
            "Shooting",
			"Hitman's", 
            "Self-Aware", 
            "Darwin's", 
            "Cozy", 
            "Cleaner's", 
            "Tribalman's", 
            "Big", 
            "Black", 
            "Eternal",
			"Wanga", 
            "Conniver's", 
            "Big", 
            "Spy-", 
            "Enthusiast's", 
            "Cloak and", 
            "Dead", 
            "Invis", 
            "Snack", 
            "Red-Tape",
			"Frying", 
            "Freedom", 
            "Bat Outta", 
            "Memory",
            "Ham", 
            "Golden Frying", 
            "Necro", 
            "Crossing", 
            "Prinny",
			"Mad"
		},
		new string[] 
        { 
            "Scatter", 
            "Blaster", 
            "Pooper", 
            "Popper", 
            "Nature", 
            "Gun", 
            "Pocket Pistol",
            "Punch", 
            "Guillotine", 
            "Cola", 
            "Milk", 
            "Cane", 
            "Basher", 
            "Blade", 
            "Stick", 
            "Assassin", 
            "Launcher", 
            "Box",
		    "Mangler", 
            "Bazooka", 
            "Strike", 
            "Shooter", 
            "Boats", 
            "Backup", 
            "Treads", 
            "Jumper", 
            "Action", 
            "Train",
		    "Plan", 
            "Thrower", 
            "Napalmer", 
            "Fury", 
            "Blower", 
            "Attack", 
            "Pummeler", 
            "Scratcher", 
            "Degree", 
            "Annihilator",
		    "Hand", 
            "Booties", 
            "Cannon", 
            "Bomber", 
            "Resistance", 
            "Targe", 
            "Headtaker", 
            "Nine Iron", 
            "Skullcutter",
		    "Curtain", 
            "Beast", 
            "Heater", 
            "Business", 
            "Bar", 
            "Sandvich", 
            "Banana", 
            "Gloves", 
            "of Boxing", 
            "Fists",
		    "Steel", 
            "Spirit", 
            "Bite", 
            "Ranger", 
            "Justice", 
            "Hospitality", 
            "Effect", 
            "Crossbow", 
            "Vow", 
            "Rifle",
		    "Sleeper", 
            "Compound", 
            "Bargain", 
            "Star", 
            "Heatmaker", 
            "Carbine", 
            "Shield", 
            "Camper", 
            "Shiv", 
            "Dresser",
		    "Prick", 
            "Reward", 
            "Kunai", 
            "Watch", 
            "Ringer", 
            "and Dagger", 
            "Pan", 
            "Staff", 
            "Hell", 
            "Maker", 
            "Shank",
		    "Guard", 
            "Machete", 
            "Pain-Bringer"
		}
    };
    public static string RandomName(byte index) => names[index][Random.Next(names[index].Length)];
    public static string RandomName() 
    {
        throw new NotImplementedException();
		//string output = ($"{prefix} " ?? "") + weaponNames[0][Random.Next(weaponNames[0].Length)];
		//output += output.EndsWith('-') ? "" : " " + weaponNames[1][Random.Next(weaponNames[1].Length)];
		//return output;
    }
}